[package]
name = "kazisitoe/kazecs"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
description = "A simple ECS system made by Kazisito"
realm = "shared"
exclude = ["Packages", "Test.server.lua", "test.project.json"]

[dependencies]
TestEZ = "roblox/testez@0.4.1"